In [2]:
import pandas as pd
import pyreadstat as st
import pingouin as pg
import numpy as np

path = r"C:\Users\HP\OneDrive\Escritorio\David Guzzi\Github\MECMT04\problem_set_6\ine.dta"

df, meta = st.read_dta(path)
df.head()

comunidad       alybnh      vestcal     vivagelo  \
0                Andalucía  4061.229980  1598.060059  7090.200195   
1                   Aragón  4108.740234  1744.599976  8370.150391   
2  Asturias(Principado de)  3644.649902  1725.589966  6449.290039   
3          Balears (Illes)  3406.590088  1318.329956  9575.309570   
4                 Canarias  3768.629883  1262.180054  7233.129883   

      mobymant       salud       transp        comu         ocio        educ  \
0  1196.560059  563.429993  2963.260010  667.609985  1253.819946  180.100006   
1  1249.680054  501.700012  2404.870117  653.630005  1689.650024  218.309998   
2  1051.199951  518.500000  2379.080078  715.820007  1459.949951  245.979996   
3  1420.140015  463.200012  2813.129883  744.380005  1591.869995  251.330002   
4   962.669983  730.369995  2926.860107  721.049988  1397.410034  209.410004   

        esparc        otros  
0  2185.179932  1282.459961  
1  2324.850098  1389.199951  
2  2103.409912  1639.849976  
3  2150.370117  1925.890015  
4  1958.500000  1210.300049

In [3]:
ndf = df.iloc[:,1:]

In [10]:
from statsmodels.multivariate.factor import Factor


# Crear el modelo de Factor Analysis
factor_model = Factor(ndf.values, n_factor=2)

# Ajustar el modelo
factor_result = factor_model.fit()

# Imprimir el resumen del análisis de factores
print(factor_result.summary())

                             Factor analysis results
                         Eigenvalues                                              
----------------------------------------------------------------------------------
   y1     y2     y3     y4     y5     y6      y7      y8      y9     y10     y11  
----------------------------------------------------------------------------------
 6.0627 1.5460 0.5667 0.2734 0.0548 0.0127 -0.0368 -0.0884 -0.1638 -0.2095 -0.4091
----------------------------------------------------------------------------------
                                                                                  
----------------------------------------------------------------------------------
                         Communality                                              
----------------------------------------------------------------------------------
        y1     y2     y3     y4     y5     y6     y7     y8     y9    y10    y11  
----------------------------------

In [13]:
from factor_analyzer import FactorAnalyzer
fa = FactorAnalyzer(n_factors=2, method='principal', rotation=None, bounds=None)  # Sin rotación

# Ajustar el análisis factorial a los datos
fa.fit(ndf)

# Obtener las cargas factoriales sin rotación
factor_loadings = fa.loadings_
pd.DataFrame(factor_loadings)

0         1
0   0.521110  0.797436
1   0.613471  0.672738
2   0.833203 -0.409309
3   0.851284 -0.004865
4   0.662390  0.429637
5   0.409202 -0.163205
6   0.892128 -0.007855
7   0.934069 -0.198391
8   0.825632 -0.379018
9   0.881599 -0.095323
10  0.719523 -0.155100

In [14]:
eigenvalues, _ = fa.get_eigenvalues()
pd.DataFrame(eigenvalues)

0
0   6.317995
1   1.683479
2   1.164594
3   0.711894
4   0.335730
5   0.246859
6   0.178187
7   0.141080
8   0.125522
9   0.060439
10  0.034220

In [15]:
fa.get_factor_variance()

(array([6.3179948 , 1.68347941]),
 array([0.57436316, 0.15304358]),
 array([0.57436316, 0.72740675]))

In [16]:
fa.transform(ndf)

array([[-0.29321894,  0.02059123],
       [ 0.06966509, -0.23847343],
       [-0.20624288, -0.31960827],
       [ 0.42339198, -1.71234539],
       [-0.39239982, -0.30875069],
       [-0.00379154,  0.87093245],
       [-0.87982744, -0.08675046],
       [-1.2876451 ,  0.19035681],
       [ 0.1317872 , -0.65043477],
       [ 0.57348669, -0.69463222],
       [-2.30695234,  0.07109428],
       [-0.32954961,  1.18187668],
       [ 1.58043394, -1.53098842],
       [-1.01727712,  0.75752754],
       [ 0.6311192 ,  0.142225  ],
       [ 1.30241386, -0.54745012],
       [ 0.08362892, -0.05424343],
       [ 1.92097791,  2.90907321]])

In [17]:
from factor_analyzer import FactorAnalyzer
fa_2 = FactorAnalyzer(n_factors=2, method='principal', rotation='varimax', bounds=None)  # Sin rotación

# Ajustar el análisis factorial a los datos
fa_2.fit(ndf)

# Obtener las cargas factoriales sin rotación
factor_loadings_2 = fa_2.loadings_
pd.DataFrame(factor_loadings)

0         1
0   0.521110  0.797436
1   0.613471  0.672738
2   0.833203 -0.409309
3   0.851284 -0.004865
4   0.662390  0.429637
5   0.409202 -0.163205
6   0.892128 -0.007855
7   0.934069 -0.198391
8   0.825632 -0.379018
9   0.881599 -0.095323
10  0.719523 -0.155100

In [18]:
eigenvalues_2, _ = fa_2.get_eigenvalues()
pd.DataFrame(eigenvalues_2)

0
0   6.317995
1   1.683479
2   1.164594
3   0.711894
4   0.335730
5   0.246859
6   0.178187
7   0.141080
8   0.125522
9   0.060439
10  0.034220

In [19]:
fa_2.transform(ndf)

array([[-0.26499301, -0.12720083],
       [ 0.17854263, -0.17275801],
       [-0.02106995, -0.37979156],
       [ 1.2152474 , -1.27849961],
       [-0.18821081, -0.46247303],
       [-0.4342608 ,  0.75495381],
       [-0.72163266, -0.51075265],
       [-1.21314317, -0.47175129],
       [ 0.43637801, -0.50000748],
       [ 0.84208   , -0.31984712],
       [-2.03989407, -1.07977574],
       [-0.87120613,  0.86396488],
       [ 2.13096178, -0.54836017],
       [-1.2588513 ,  0.15490032],
       [ 0.47805752,  0.43589036],
       [ 1.40267854,  0.1687495 ],
       [ 0.09951397, -0.00575456],
       [ 0.22980205,  3.4785132 ]])

In [22]:
pd.concat([pd.DataFrame(factor_loadings), pd.DataFrame(factor_loadings_2)], axis=1)

0         1         0         1
0   0.521110  0.797436  0.058241  0.950825
1   0.613471  0.672738  0.200206  0.888167
2   0.833203 -0.409309  0.926583  0.056612
3   0.851284 -0.004865  0.742163  0.417016
4   0.662390  0.429637  0.363010  0.701122
5   0.409202 -0.163205  0.436351  0.060663
6   0.892128 -0.007855  0.779135  0.434628
7   0.934069 -0.198391  0.909865  0.289809
8   0.825632 -0.379018  0.905015  0.079188
9   0.881599 -0.095323  0.813268  0.353409
10  0.719523 -0.155100  0.702006  0.221263

In [23]:
import pandas as pd
import pyreadstat as st
import pingouin as pg
import numpy as np

path = r"C:\Users\HP\OneDrive\Escritorio\David Guzzi\Github\MECMT04\problem_set_6\eurosec.dta"

df, meta = st.read_dta(path)
df.head()

pais         s1   s2         s3   s4   s5         s6   s7  \
0        Belgica   3.300000  0.9  27.600000  0.9  8.2  19.100000  6.2   
1      Dinamarca   9.200000  0.1  21.799999  0.6  8.3  14.600000  6.5   
2        Francia  10.800000  0.8  27.500000  0.9  8.9  16.799999  6.0   
3  Alemania Este   6.700000  1.3  35.799999  0.9  7.3  14.400000  5.0   
4        Irlanda  23.200001  1.0  20.700001  1.3  7.5  16.799999  2.8   

          s8   s9  
0  26.600000  7.2  
1  32.200001  7.1  
2  22.600000  5.7  
3  22.299999  6.1  
4  20.799999  6.1

In [24]:
df.describe()

s1         s2         s3         s4         s5         s6  \
count  26.000000  26.000000  26.000000  26.000000  26.000000  26.000000   
mean   19.130769   1.253846  27.007692   0.907692   8.165385  12.957692   
std    15.546570   0.970044   7.007763   0.376216   1.645586   4.575253   
min     2.700000   0.100000   7.900000   0.100000   2.800000   5.200000   
25%     7.700000   0.525000  23.000000   0.600000   7.525000   9.250000   
50%    14.450000   0.950000  27.550000   0.850000   8.350000  14.400000   
75%    23.675001   1.800000  30.200001   1.175000   8.975000  16.875000   
max    66.800003   3.100000  41.200001   1.900000  11.500000  19.100000   

              s7         s8         s9  
count  26.000000  26.000000  26.000000  
mean    4.000000  20.023077   6.546154  
std     2.806564   6.829542   1.391468  
min     0.500000   5.300000   3.200000  
25%     1.225000  16.250000   5.700000  
50%     4.650000  19.650001   6.700000  
75%     5.925000  24.125000   7.075000  
max    11.300000  32.400002   9.400000

In [26]:
ndf = df.iloc[:,1:]

In [43]:
from factor_analyzer import FactorAnalyzer
fa = FactorAnalyzer(n_factors=5, method='principal', rotation=None)  # Sin rotación

# Ajustar el análisis factorial a los datos
fa.fit(ndf)

# Obtener las cargas factoriales sin rotación
factor_loadings = fa.loadings_
pd.DataFrame(factor_loadings)

0         1         2         3         4
0 -0.978123  0.078221 -0.051026  0.028713  0.156769
1 -0.002471  0.901696  0.210816  0.063908 -0.120684
2  0.648909  0.518205  0.157732 -0.345132 -0.283726
3  0.477522  0.381073  0.588190  0.392223  0.217551
4  0.607237  0.074856 -0.160728 -0.666478  0.347580
5  0.707591 -0.511080  0.120656 -0.050018 -0.208999
6  0.138885 -0.662177  0.615738 -0.051424  0.206051
7  0.723444 -0.323313 -0.326972  0.411091 -0.162406
8  0.685002  0.295685 -0.393228  0.313503  0.378051

In [39]:
eigenvalues_3, _ = fa.get_eigenvalues()
eigenvalues_3

array([3.48715124e+00, 2.13017319e+00, 1.09895763e+00, 9.94482974e-01,
       5.43217767e-01, 3.83427644e-01, 2.25754046e-01, 1.36789882e-01,
       4.56251076e-05])

In [40]:
fa.transform(ndf)

array([[ 0.72045849, -0.87562986,  0.93292582,  0.0311938 , -0.28749589],
       [ 0.53917889, -1.75338782, -0.68343523, -0.96768963, -0.48717721],
       [ 0.47501449, -0.14309091,  0.59212826, -0.39778984, -0.48313581],
       [ 0.6572684 , -0.08654085,  0.22626469,  1.74356836, -1.03116511],
       [-0.46388651, -0.64762176,  0.72687195, -0.44550363,  0.83879744],
       [ 0.43874569,  0.51832554, -0.02357688, -1.08930166, -1.19260565],
       [ 0.62296547,  0.50065379,  1.15444367, -0.03495672, -0.12876898],
       [ 0.78604769, -0.87601276,  0.36050335, -1.77422472,  0.22232112],
       [ 0.69100187, -1.27164692,  0.58501396,  1.19198596,  0.28712387],
       [ 0.33877578,  0.71477112,  1.3125017 ,  0.01922312,  0.69056983],
       [ 0.1564758 , -0.84726725,  0.46244199,  0.29900658,  0.63333441],
       [-1.377586  ,  0.62003345,  0.3542607 , -1.19894755,  0.18433577],
       [ 0.45109012, -1.13476398,  0.28744169, -0.97324393,  0.52451497],
       [-0.43372938,  0.36748723, -0.1