In [343]:
import pandas as pd
import numpy as np

np.set_printoptions(precision=4)
pd.set_option('display.float_format', '{:.4f}'.format)
# path = r"C:\Users\HP\OneDrive\Escritorio\David Guzzi\DiTella\MEC\Materias\2024 2T\[MT04] Análisis Estadístico Multivariado\Guías prácticas\Problem Set 5-20240906\FA.xlsx"

# df = pd.read_excel(path)
# df


In [3]:
# df.to_stata(r"C:\Users\HP\OneDrive\Escritorio\David Guzzi\DiTella\MEC\Materias\2024 2T\[MT04] Análisis Estadístico Multivariado\Guías prácticas\Problem Set 5-20240906\FA.dta")

In [22]:
data = np.array([
    [1, 5, 5, 1, 1],
    [8, 9, 7, 9, 8],
    [9, 8, 9, 9, 8],
    [9, 9, 9, 9, 9],
    [1, 9, 1, 1, 9],
    [9, 7, 7, 9, 9],
    [9, 7, 9, 9, 7]
])

In [35]:
data_cov = np.cov(data, rowvar=False)
data_cov_inv = np.linalg.inv(data_cov)
data_cov_inv_d = np.diag(data_cov_inv)
data_cov_d = np.diag(data_cov)

data_cov_d - (1/data_cov_inv_d)


array([14.619 ,  2.2381,  8.5714, 15.2381,  8.2381])

In [36]:
data_cov_d

array([14.619 ,  2.2381,  8.5714, 15.2381,  8.2381])

In [34]:
data_cor = np.corrcoef(data, rowvar=False)
data_inv = np.linalg.inv(data_cor)
data_inv_d = np.diag(data_inv)
com = 1 - (1/data_inv_d)
pd.DataFrame(data_inv)

0                     1                     2  \
0 -2644311556751862.0000 -344882461543805.6875  674929534706399.2500   
1  -344882461543805.9375  -44981050730122.6016   88027206440106.9531   
2   674929534706398.2500   88027206440106.7812 -172267853860047.3438   
3  1799812092550373.0000  234739217173618.4062 -459380943626833.1875   
4   661675771094734.5000   86298593710095.0156 -168884986026386.2812   

                       3                     4  
0  1799812092550371.7500  661675771094734.8750  
1   234739217173618.3438   86298593710095.0938  
2  -459380943626832.1875 -168884986026386.1250  
3 -1225015849671483.2500 -450359962737050.1875  
4  -450359962737049.6250 -165568548432159.7188

In [30]:
data_inv_d

array([-2.6443e+15, -4.4981e+13, -1.7227e+14, -1.2250e+15, -1.6557e+14])

In [18]:
data_cor = np.corrcoef(data, rowvar=False)
C, D, V = np.linalg.svd(data_cor, full_matrices=False)
loadings = C * np.sqrt(D)
pd.DataFrame(loadings)


0         1         2         3             4
0 -0.969455  0.231148  0.078451 -0.023928 -8.292461e-09
1 -0.519402 -0.806945 -0.280349 -0.021568 -1.081538e-09
2 -0.784517  0.587241 -0.167545  0.107744  2.116553e-09
3 -0.970870  0.209949  0.039351 -0.108552  5.644142e-09
4 -0.703964 -0.666927  0.231258  0.078502  2.074990e-09

In [49]:
corr = df.corr().values
max = np.array([corr[:, i][corr[:, i] < 1].max() for i in range(corr.shape[1])])
corr_max = corr.copy()
np.fill_diagonal(corr_max, max)
corr_max


array([[0.26418458, 0.26418458],
       [0.26418458, 0.26418458]])

In [47]:
C, D, V = np.linalg.svd(corr_max, full_matrices=False)
D_o = sorted(D, reverse=True)
loadings = C * np.sqrt(D_o)
pd.DataFrame(loadings)

0             1
0 -0.513989 -3.239622e-09
1 -0.513989  3.239622e-09

In [48]:
D_o

[0.5283691548027929, 2.0990295514250575e-17]

In [36]:
# data = np.array([
#     [1, 5, 5, 1, 1],
#     [8, 9, 7, 9, 8],
#     [9, 8, 9, 9, 8],
#     [9, 9, 9, 9, 9],
#     [1, 9, 1, 1, 9],
#     [9, 7, 7, 9, 9],
#     [9, 7, 9, 9, 7]
# ])
# correlacion = np.corrcoef(data, rowvar=False)
# correlacion


R = np.array([
    [1.000, 0.296, 0.881, 0.995, 0.545],
    [0.296, 1.000, -0.022, 0.326, 0.837],
    [0.881, -0.022, 1.000, 0.867, 0.130],
    [0.995, 0.326, 0.867, 1.000, 0.544],
    [0.545, 0.837, 0.130, 0.544, 1.000]
])

In [37]:
# Obtener el máximo de cada columna
maximos = np.array([R[:, i][R[:, i] < 1].max() for i in range(R.shape[1])])

# Asignar los máximos a la diagonal principal
corr_m = R.copy()
np.fill_diagonal(corr_m, maximos)

corr_m

array([[ 0.995,  0.296,  0.881,  0.995,  0.545],
       [ 0.296,  0.837, -0.022,  0.326,  0.837],
       [ 0.881, -0.022,  0.881,  0.867,  0.13 ],
       [ 0.995,  0.326,  0.867,  0.995,  0.544],
       [ 0.545,  0.837,  0.13 ,  0.544,  0.837]])

In [40]:
C, D, V = np.linalg.svd(corr_m, full_matrices=False)
D_o = sorted(D, reverse=True)
D_o

[3.2017093090737263,
 1.3944390756838965,
 0.08030346115353326,
 0.029317098629336614,
 0.00016202223342619344]

In [41]:
C

array([[-0.54801288,  0.17703557,  0.43482521,  0.4128932 , -0.55568564],
       [-0.27205858, -0.6555723 ,  0.35020688, -0.60069019, -0.11285179],
       [-0.43126509,  0.46085993, -0.49431898, -0.55340045, -0.22586551],
       [-0.54855994,  0.15869823,  0.20994059,  0.04883377,  0.79210926],
       [-0.37250292, -0.5489138 , -0.63234157,  0.40006713, -0.00506389]])

In [43]:
loadings = C * np.sqrt(D_o)
pd.DataFrame(loadings)

0         1         2         3         4
0 -0.980577  0.209055  0.123220  0.070697 -0.007073
1 -0.486803 -0.774142  0.099241 -0.102852 -0.001436
2 -0.771676  0.544213 -0.140079 -0.094755 -0.002875
3 -0.981556  0.187401  0.059493  0.008361  0.010083
4 -0.666531 -0.648192 -0.179192  0.068500 -0.000064

In [19]:


from numpy.linalg import eigh
eigenvalues, eigenvectors = eigh(correlacion)

eigenvectors


array([[-0.78859185, -0.13680245,  0.19148531,  0.18636648, -0.5366646 ],
       [-0.10285153, -0.12331285, -0.68428658, -0.65061165, -0.28752715],
       [ 0.20127883,  0.61600625, -0.40895166,  0.47347196, -0.4342879 ],
       [ 0.53674354, -0.62062607,  0.0960492 ,  0.16927454, -0.53744798],
       [ 0.19732626,  0.44881913,  0.56446288, -0.53771969, -0.38969594]])

In [21]:
C, D, V = np.linalg.svd(correlacion, full_matrices=False)
D_o = sorted(D, reverse=True)
D_o

[3.263245029034827,
 1.5383125277506948,
 0.16785005049901378,
 0.03059239271546363,
 1.1057635293408557e-16]

In [12]:
C

array([[-0.53673007,  0.18598191,  0.18991841, -0.12479313, -0.79100521],
       [-0.28746718, -0.65056657, -0.68488713, -0.11981409, -0.10344059],
       [-0.43435455,  0.47368768, -0.40694897,  0.61366343,  0.2115794 ],
       [-0.53739095,  0.16927968,  0.09532905, -0.62938958,  0.52662747],
       [-0.38965441, -0.53771576,  0.5658317 ,  0.44424905,  0.20373628]])

In [22]:
loadings = C * np.sqrt(D_o)
loadings

array([[-9.69455305e-01,  2.31147968e-01,  7.84505865e-02,
        -2.39276806e-02, -8.29246060e-09],
       [-5.19402104e-01, -8.06945347e-01, -2.80348839e-01,
        -2.15682580e-02, -1.08153830e-09],
       [-7.84517390e-01,  5.87241242e-01, -1.67545477e-01,
         1.07743689e-01,  2.11655338e-09],
       [-9.70870447e-01,  2.09949055e-01,  3.93508828e-02,
        -1.08551727e-01,  5.64414236e-09],
       [-7.03964442e-01, -6.66926884e-01,  2.31257661e-01,
         7.85015230e-02,  2.07499008e-09]])

In [16]:
array_cuadrado = np.square(loadings)

# Sumar los cuadrados por cada fila
suma_filas = np.sum(array_cuadrado, axis=1)
suma_filas

array([1., 1., 1., 1., 1.])

In [51]:
data = np.array([
    [1, 5, 5, 1, 1],
    [8, 9, 7, 9, 8],
    [9, 8, 9, 9, 8],
    [9, 9, 9, 9, 9],
    [1, 9, 1, 1, 9],
    [9, 7, 7, 9, 9],
    [9, 7, 9, 9, 7]
])

pd.DataFrame(data).to_stata(r"C:\Users\HP\OneDrive\Escritorio\David Guzzi\DiTella\MEC\Materias\2024 2T\[MT04] Análisis Estadístico Multivariado\Guías prácticas\Problem Set 5-20240906\FA.dta")

C:\Users\HP\AppData\Local\Temp\ipykernel_13820\3666724846.py:11: InvalidColumnName: 
Not all pandas column names were valid Stata variable names.
The following replacements have been made:

    0   ->   _0
    1   ->   _1
    2   ->   _2
    3   ->   _3
    4   ->   _4

If this is not what you expect, please make sure you have Stata-compliant
column names in your DataFrame (strings only, max 32 characters, only
alphanumerics and underscores, no Stata reserved words)

  pd.DataFrame(data).to_stata(r"C:\Users\HP\OneDrive\Escritorio\David Guzzi\DiTella\MEC\Materias\2024 2T\[MT04] Análisis Estadístico Multivariado\Guías prácticas\Problem Set 5-20240906\FA.dta")


In [14]:
final = pd.read_excel(r"C:\Users\HP\OneDrive\Escritorio\David Guzzi\Github\MECMT04\TP AEM - database.xlsx")

final.columns = [f"X{i}" for i in range(len(final.columns))]

# final.to_stata(r"C:\Users\HP\OneDrive\Escritorio\David Guzzi\DiTella\MEC\Materias\2024 2T\[MT04] Análisis Estadístico Multivariado\Guías prácticas\Problem Set 5-20240906\final.dta")

In [76]:
final.head()

X0   X1      X2      X3     X4     X5     X6     X7      X8
0  Argentina  ARG 42.5908 14.9117 0.8813 1.0457 5.3186 7.3309  8.0090
1  Australia  AUS 47.1238  3.9746 2.1059 0.6622 2.1131 2.5583 13.8760
2    Austria  AUT 32.1281 16.0631 1.5208 1.8149 1.0524 3.6561 41.4850
3    Belgium  BEL 44.7960 28.3120 1.2331 1.0485 0.6700 0.9196  1.9590
4     Canada  CAN  6.4344  4.3107 3.6934 0.8181 1.6971 1.5105 18.5180

In [77]:
final = final.iloc[:,2:].values
data_cor = np.corrcoef(final, rowvar=False)
data_inv = np.linalg.inv(data_cor)
data_inv_d = np.diag(data_inv)
com = 1 - (1/data_inv_d)
np.fill_diagonal(data_cor, com)
C, D, V = np.linalg.svd(data_cor, full_matrices=False, hermitian=True)
loadings = C * np.sqrt(D)
pd.DataFrame(loadings)

0       1       2       3       4       5       6
0 -0.3620 -0.5729  0.3125 -0.2164  0.1097 -0.0770 -0.0963
1 -0.5573 -0.6024 -0.0920  0.2949  0.1548  0.0332  0.0562
2  0.4277  0.0578 -0.4933  0.1525  0.1836 -0.1280 -0.0935
3 -0.0015 -0.4064 -0.6090 -0.2837 -0.0612 -0.0261  0.0549
4  0.8288 -0.3121  0.1079 -0.0507  0.1651  0.2626  0.0063
5  0.7171 -0.4543  0.2437  0.0964 -0.1480 -0.2293  0.0380
6 -0.0502 -0.3159 -0.1551  0.1343 -0.3320  0.1569 -0.0813

In [59]:
C

array([[-0.2678, -0.5098,  0.3461, -0.4184,  0.2274, -0.1867, -0.5358],
       [-0.4122, -0.536 , -0.1019,  0.5702,  0.3207,  0.0804,  0.3129],
       [ 0.3163,  0.0515, -0.5463,  0.2948,  0.3804, -0.3101, -0.5206],
       [-0.0011, -0.3615, -0.6744, -0.5486, -0.1268, -0.0632,  0.3056],
       [ 0.6129, -0.2777,  0.1194, -0.0981,  0.3422,  0.6364,  0.0351],
       [ 0.5304, -0.4042,  0.2698,  0.1864, -0.3068, -0.5558,  0.2117],
       [-0.0372, -0.2811, -0.1718,  0.2598, -0.6881,  0.3803, -0.4523]])

In [54]:
np.sort(D)

array([0.0323, 0.1703, 0.2328, 0.2674, 0.8155, 1.2632, 1.8282])

In [68]:
from numpy.linalg import eigh
eigenvalues, eigenvectors = eigh(data_cor)
np.sort(eigenvalues)

eigenvectors * np.sqrt(eigenvalues)

C:\Users\HP\AppData\Local\Temp\ipykernel_11736\3228913241.py:5: RuntimeWarning: invalid value encountered in sqrt
  eigenvectors * np.sqrt(eigenvalues)


array([[    nan,     nan,     nan,  0.1097,  0.3125, -0.5729, -0.362 ],
       [    nan,     nan,     nan,  0.1548, -0.092 , -0.6024, -0.5573],
       [    nan,     nan,     nan,  0.1836, -0.4933,  0.0578,  0.4277],
       [    nan,     nan,     nan, -0.0612, -0.609 , -0.4064, -0.0015],
       [    nan,     nan,     nan,  0.1651,  0.1079, -0.3121,  0.8288],
       [    nan,     nan,     nan, -0.148 ,  0.2437, -0.4543,  0.7171],
       [    nan,     nan,     nan, -0.332 , -0.1551, -0.3159, -0.0502]])

In [61]:
eigenvalues

array([-0.2674, -0.1703, -0.0323,  0.2328,  0.8155,  1.2632,  1.8282])

In [60]:
loadings3 = C * np.sqrt(eigenvalues)
loadings3

C:\Users\HP\AppData\Local\Temp\ipykernel_11736\3645955264.py:1: RuntimeWarning: invalid value encountered in sqrt
  loadings3 = C * np.sqrt(eigenvalues)


array([[    nan,     nan,     nan, -0.2019,  0.2053, -0.2098, -0.7245],
       [    nan,     nan,     nan,  0.2751,  0.2896,  0.0904,  0.4231],
       [    nan,     nan,     nan,  0.1422,  0.3435, -0.3485, -0.7039],
       [    nan,     nan,     nan, -0.2647, -0.1145, -0.0711,  0.4132],
       [    nan,     nan,     nan, -0.0473,  0.309 ,  0.7153,  0.0474],
       [    nan,     nan,     nan,  0.09  , -0.277 , -0.6247,  0.2862],
       [    nan,     nan,     nan,  0.1253, -0.6213,  0.4274, -0.6115]])

In [56]:
import pandas as pd
import numpy as np
from scipy.linalg import eigh

# Cargar los datos desde el archivo Excel
final = pd.read_excel(r"C:\Users\HP\OneDrive\Escritorio\David Guzzi\Github\MECMT04\TP AEM - database.xlsx")

# Renombrar las columnas
final.columns = [f"X{i}" for i in range(len(final.columns))]

# Seleccionar los datos a partir de la tercera columna
final = final.iloc[:, 2:].values

# Calcular la matriz de correlación
data_cor = np.corrcoef(final, rowvar=False)

# Calcular la matriz inversa de la correlación
data_inv = np.linalg.inv(data_cor)
data_inv_d = np.diag(data_inv)

# Calcular la matriz de comunalidades
com = 1 - (1 / data_inv_d)

# Rellenar la diagonal de la matriz de correlación
np.fill_diagonal(data_cor, com)

# # Paso 1: Descomposición SVD
# C, D, V = np.linalg.svd(data_cor, full_matrices=False)

from sklearn.utils.extmath import randomized_svd
C, D, V = randomized_svd(data_cor, n_components=17, random_state=1234567890)

# Paso 2: Obtener autovalores y autovectores
eigenvalues, eigenvectors = eigh(data_cor)

# Paso 3: Filtrar y ordenar autovalores positivos
# positive_indices = eigenvalues > 0
# sorted_indices = np.argsort(eigenvalues[positive_indices])[::-1]  # Índices para ordenar de mayor a menor
# positive_eigenvalues = eigenvalues[positive_indices][sorted_indices]

# Filtrar los autovectores de SVD (C) usando los índices positivos


# Paso 4: Realizar la multiplicación para obtener los loadings
loadings = C * np.sqrt(D)
loadings = loadings[:, ~np.isnan(loadings).any(axis=0)]

# Resultados
# print("Autovalores positivos ordenados:", positive_eigenvalues)
# print("Autovectores de SVD correspondientes ordenados:\n", eigenvectors)
print("Loadings:\n", pd.DataFrame(loadings))


Loadings:
           0         1         2         3         4         5         6
0 -0.362026  0.572944 -0.312506 -0.216358 -0.109711 -0.077034  0.096279
1 -0.557272  0.602441  0.092032  0.294884 -0.154758  0.033189 -0.056226
2  0.427731 -0.057843  0.493310  0.152453 -0.183555 -0.127969  0.093550
3 -0.001547  0.406351  0.609016 -0.283701  0.061187 -0.026100 -0.054910
4  0.828759  0.312065 -0.107862 -0.050714 -0.165089  0.262619 -0.006299
5  0.717103  0.454272 -0.243655  0.096408  0.148018 -0.229342 -0.038032
6 -0.050240  0.315936  0.155129  0.134338  0.331991  0.156915  0.081274


In [12]:
from sklearn.utils.extmath import randomized_svd
from tabulate import tabulate
import textwrap

def principal_factor_method(X, n_components = None):
        """
        Returns the loading matrix of the specified number of principal components.
        If not specified retuns for all the components whose Eigen value greater than 0
        """

        X_corr = np.corrcoef(X, rowvar=False)
        X_corr_inv = np.linalg.inv(X_corr)
        X_corr_inv_diag = np.diag(X_corr_inv)
        R = 1 - (1 / X_corr_inv_diag)
        np.fill_diagonal(X_corr, R)
        eigenvalues, _ = np.linalg.eig(X_corr)
        #agregar la otra opción. 
        eigenvectors, eigenvalues_p, _ = randomized_svd(X_corr, n_components=X_corr.shape[1], random_state=1234567890)     
        
        loadings = eigenvectors * np.sqrt(eigenvalues_p)
        positive_filter = np.array([i for i, value in enumerate(np.round(eigenvalues_p, decimals=10)) if value in np.round(eigenvalues, decimals=10)])
        postive_loadings = loadings[:, positive_filter]

        if n_components == None:
            postive_loadings
        else:
            postive_loadings = postive_loadings[:, :n_components]
                    
        loadings_matrix = pd.DataFrame(postive_loadings, columns=[f"Factor {i+1}" for i in range(postive_loadings.shape[1])], index=[f"x{i+1}" for i in range(postive_loadings.shape[0])]).reset_index(names='Variable')
        communalities, uniquenesses = np.sum((postive_loadings**2), axis=1), 1 - np.sum((postive_loadings**2), axis=1)
        loadings_matrix = pd.concat([loadings_matrix, pd.DataFrame(uniquenesses, columns=['Uniqueness']), pd.DataFrame(communalities, columns=['Communality'])], axis=1)
        eigenv_matrix = pd.DataFrame(np.sort(eigenvalues)[::-1], columns=['Eigenvalue'], index=[f"Factor {i+1}" for i in range(eigenvalues.shape[0])]).reset_index(names='Factor')
        eigenv_proportion = [np.sort(eigenvalues)[::-1][i] / np.sum(np.sort(eigenvalues)[::-1]) for i in range(len(eigenvalues))]
        eigenv_proportion_cs = np.cumsum(eigenv_proportion)
        eigenv_matrix = pd.concat([eigenv_matrix, pd.DataFrame(eigenv_proportion, columns=['Proportion']), pd.DataFrame(eigenv_proportion_cs, columns=['Cumulative'])], axis=1)

        # print(f"-------------Resultados de Factor Analysis-------------")
        # print(tabulate(eigenv_matrix, headers='keys', tablefmt="fancy_grid", showindex=False, floatfmt=".4f"))
        # print(f"-------------------------------------------------------")
        # print(tabulate(loadings_matrix, headers='keys', tablefmt="fancy_grid", showindex=False, floatfmt=".4f"))
        # Definir las tablas como cadenas
        eigenv_table = tabulate(eigenv_matrix, headers='keys', tablefmt="fancy_grid", showindex=False, floatfmt=".4f")
        loadings_table = tabulate(loadings_matrix, headers='keys', tablefmt="fancy_grid", showindex=False, floatfmt=".4f")

        # Separar las líneas de cada tabla
        eigenv_lines = eigenv_table.splitlines()
        loadings_lines = loadings_table.splitlines()

        # Asegurarse de que ambas tengan la misma cantidad de líneas
        max_lines = max(len(eigenv_lines), len(loadings_lines))
        eigenv_lines += [''] * (max_lines - len(eigenv_lines))
        loadings_lines += [''] * (max_lines - len(loadings_lines))

        # Combinar ambas tablas en una sola salida
        combined_output = "\n".join(f"{eigenv: <40}   {loading}" for eigenv, loading in zip(eigenv_lines, loadings_lines))
        bold_start = "\033[1m"
        bold_end = "\033[0m"
        # Imprimir el resultado
        print(f"{bold_start}Resultados de Factor Analysis{bold_end}")
        print(combined_output)

In [2]:
import pandas as pd
import pyreadstat as st
import pingouin as pg
import numpy as np

path = r"C:\Users\HP\OneDrive\Escritorio\David Guzzi\Github\MECMT04\problem_set_5\ind.dta"

df, meta = st.read_dta(path)

In [354]:
df.head(1)

pais      x1      x2     x3      x4     x5      x6     x7      x8  \
0  Albania 41.7500 29.1300 0.6900 17.6000 2.3400 59.6000 7.3000 95.0000   

       x9     x10    x11    x12     x13     x14     x15     x16     x17  
0 37.4900 19.0100 4.3200 1.1400 73.3500 36.6000 22.0000 25.0000 -0.0500

In [17]:
principal_factor_method(final.iloc[:,2:].values)

Resultados de Factor Analysis
╒══════════╤══════════════╤══════════════╤══════════════╕   ╒════════════╤════════════╤════════════╤════════════╤════════════╤══════════════╤═══════════════╕
│ Factor   │   Eigenvalue │   Proportion │   Cumulative │   │ Variable   │   Factor 1 │   Factor 2 │   Factor 3 │   Factor 4 │   Uniqueness │   Communality │
╞══════════╪══════════════╪══════════════╪══════════════╡   ╞════════════╪════════════╪════════════╪════════════╪════════════╪══════════════╪═══════════════╡
│ Factor 1 │       1.8282 │       0.4982 │       0.4982 │   │ x1         │    -0.3620 │     0.5729 │    -0.3125 │    -0.1097 │       0.4310 │        0.5690 │
├──────────┼──────────────┼──────────────┼──────────────┤   ├────────────┼────────────┼────────────┼────────────┼────────────┼──────────────┼───────────────┤
│ Factor 2 │       1.2632 │       0.3442 │       0.8424 │   │ x2         │    -0.5573 │     0.6024 │     0.0920 │    -0.1548 │       0.2941 │        0.7059 │
├──────────┼──────────

In [30]:
n_components = 4
X_corr = np.corrcoef(final.iloc[:,2:].values, rowvar=False)
X_corr_inv = np.linalg.inv(X_corr)
X_corr_inv_diag = np.diag(X_corr_inv)
R = 1 - (1 / X_corr_inv_diag)
np.fill_diagonal(X_corr, R)
eigenvalues, _ = np.linalg.eig(X_corr)
#agregar la otra opción. 
eigenvectors, eigenvalues_p, _ = randomized_svd(X_corr, n_components=X_corr.shape[1], random_state=1234567890)     

loadings = eigenvectors * np.sqrt(eigenvalues_p)
positive_filter = np.array([i for i, value in enumerate(np.round(eigenvalues_p, decimals=10)) if value in np.round(eigenvalues, decimals=10)])
postive_loadings = loadings[:, positive_filter]

if n_components == None:
    postive_loadings
else:
    postive_loadings = postive_loadings[:, :n_components]
            
loadings_matrix = pd.DataFrame(postive_loadings, columns=[f"Factor {i+1}" for i in range(postive_loadings.shape[1])], index=[f"x{i+1}" for i in range(postive_loadings.shape[0])]).reset_index(names='Variable')
communalities, uniquenesses = np.sum((postive_loadings**2), axis=1), 1 - np.sum((postive_loadings**2), axis=1)
loadings_matrix = pd.concat([loadings_matrix, pd.DataFrame(uniquenesses, columns=['Uniqueness']), pd.DataFrame(communalities, columns=['Communality'])], axis=1)
eigenv_matrix = pd.DataFrame(np.sort(eigenvalues)[::-1], columns=['Eigenvalue'], index=[f"Factor {i+1}" for i in range(eigenvalues.shape[0])]).reset_index(names='Factor')
eigenv_proportion = [np.sort(eigenvalues)[::-1][i] / np.sum(np.sort(eigenvalues)[::-1]) for i in range(len(eigenvalues))]
eigenv_proportion_cs = np.cumsum(eigenv_proportion)
eigenv_matrix = pd.concat([eigenv_matrix, pd.DataFrame(eigenv_proportion, columns=['Proportion']), pd.DataFrame(eigenv_proportion_cs, columns=['Cumulative'])], axis=1)

ee = pd.DataFrame(postive_loadings @ postive_loadings.T + np.diag(uniquenesses))

In [29]:
re = pd.DataFrame(np.corrcoef(final.iloc[:,2:].values, rowvar=False))

In [33]:
re

0         1         2         3         4         5         6
0  1.000000  0.606901 -0.307895 -0.021763 -0.059553  0.067420  0.147628
1  0.606901  1.000000 -0.234851  0.373682 -0.252337 -0.194236  0.140976
2 -0.307895 -0.234851  1.000000  0.310085  0.355457  0.092595 -0.032179
3 -0.021763  0.373682  0.310085  1.000000  0.041856  0.063429  0.289918
4 -0.059553 -0.252337  0.355457  0.041856  1.000000  0.802792 -0.048469
5  0.067420 -0.194236  0.092595  0.063429  0.802792  1.000000  0.144964
6  0.147628  0.140976 -0.032179  0.289918 -0.048469  0.144964  1.000000

In [31]:
re - ee

0         1             2         3             4             5  \
0  0.000000  0.071771  1.411969e-02 -0.058105  9.864752e-03  6.853152e-03   
1  0.071771  0.000000 -3.544898e-02  0.081438  5.884523e-03 -2.295594e-02   
2  0.014120 -0.035449 -1.110223e-16  0.045048  4.192798e-02 -4.048848e-02   
3 -0.058105  0.081438  4.504802e-02  0.000000 -7.879195e-03  1.927687e-02   
4  0.009865  0.005885  4.192798e-02 -0.007879 -1.110223e-16  6.487921e-02   
5  0.006853 -0.022956 -4.048848e-02  0.019277  6.487921e-02 -2.220446e-16   
6  0.033328 -0.040252 -8.003081e-03  0.046670 -3.388416e-02  2.612708e-02   

          6  
0  0.033328  
1 -0.040252  
2 -0.008003  
3  0.046670  
4 -0.033884  
5  0.026127  
6  0.000000

In [22]:
print(np.diag(uniquenesses))

[[0.43097485 0.         0.         0.         0.         0.
  0.        ]
 [0.         0.29409291 0.         0.         0.         0.
  0.        ]
 [0.         0.         0.53665307 0.         0.         0.
  0.        ]
 [0.         0.         0.         0.46023243 0.         0.
  0.        ]
 [0.         0.         0.         0.         0.17688512 0.
  0.        ]
 [0.         0.         0.         0.         0.         0.19812327
  0.        ]
 [0.         0.         0.         0.         0.         0.
  0.7633776 ]]


In [222]:
X_corr = np.corrcoef(final, rowvar=False)
X_corr_inv = np.linalg.inv(X_corr)
X_corr_inv_diag = np.diag(X_corr_inv)
R = 1 - (1 / X_corr_inv_diag)
np.fill_diagonal(X_corr, R)
eigenvalues, _ = np.linalg.eig(X_corr)
eigenvectors, eigenvalues_p, _ = randomized_svd(X_corr, n_components=X_corr.shape[1], random_state=1234567890)     

d = np.sort(eigenvalues)[::-1]
s = [d[i] / np.sum(d) for i in range(len(d))]
np.cumsum(s)

array([0.49818336, 0.84241787, 1.06463127, 1.12807119, 1.11927228,
       1.07286987, 1.        ])

In [201]:
eigenvalues

array([ 1.82817372,  1.26323065,  0.81545216,  0.23280422, -0.03228917,
       -0.26740915, -0.17028201])

In [190]:
loadings

array([[ 1.01057828e-01,  7.29007131e-03, -2.52898016e-01,
        -1.50565095e-01, -5.30180733e-02, -6.88053261e-02,
         3.05244510e-01,  2.05285650e-02, -4.40649698e-04,
         4.87900996e-04],
       [ 7.49810279e-01, -4.41252699e-03, -1.38452581e-01,
        -2.42232654e-01, -3.93720652e-02, -6.33832867e-02,
        -1.63825113e-01,  1.51742224e-01, -3.01185471e-02,
        -4.98656318e-03],
       [-6.55061596e-01, -2.00894170e-02,  3.68260358e-01,
         1.09380049e-01,  6.35223365e-02,  9.59862892e-02,
         7.37313145e-02,  1.53477983e-01, -1.56217906e-02,
        -3.29578437e-03],
       [-4.28423029e-01,  8.21047856e-01,  4.32259646e-02,
        -3.80625783e-02, -6.08393768e-02,  5.34371170e-02,
         2.55980464e-05,  3.13204235e-02, -5.74039803e-02,
        -6.41271001e-04],
       [ 8.12403195e-01,  1.09483165e-01,  2.01969214e-01,
         1.14853169e-02,  5.97661915e-02,  1.51123060e-01,
        -3.99960626e-02, -1.63161883e-02,  6.17820667e-02,
         1.

In [152]:
X_corr = np.corrcoef(df.iloc[:,1:].values, rowvar=False)
X_corr_inv = np.linalg.inv(X_corr)
X_corr_inv_diag = np.diag(X_corr_inv)
R = 1 - (1 / X_corr_inv_diag)
np.fill_diagonal(X_corr, R)
eigenvalues, _ = np.linalg.eig(X_corr)
eigenvectors, D, _ = randomized_svd(X_corr, n_components=X_corr.shape[1], random_state=1234567890)
pd.DataFrame(eigenvectors * np.sqrt(D))


0       1       2       3       4       5       6       7       8   \
0   0.1011  0.0073 -0.2529 -0.1506 -0.0530 -0.0688  0.1017  0.3052  0.0365   
1   0.7498 -0.0044 -0.1385 -0.2422 -0.0394 -0.0634 -0.0784 -0.1638  0.1565   
2  -0.6551 -0.0201  0.3683  0.1094  0.0635  0.0960 -0.0448  0.0737 -0.1604   
3  -0.4284  0.8210  0.0432 -0.0381 -0.0608  0.0534 -0.0536  0.0000 -0.0754   
4   0.8124  0.1095  0.2020  0.0115  0.0598  0.1511 -0.0483 -0.0400 -0.1066   
5  -0.7793 -0.1949  0.4131 -0.3098 -0.0566 -0.0920 -0.0299  0.0597  0.1119   
6  -0.1398  0.1956  0.0440  0.1209  0.4829 -0.2649  0.1990 -0.0576 -0.0307   
7  -0.7332 -0.0219 -0.3124  0.0741  0.0689  0.0115 -0.0464  0.0677  0.0714   
8  -0.2591  0.7625 -0.2627 -0.3534 -0.0507  0.1093  0.1347 -0.0099 -0.0343   
9  -0.2370  0.3700  0.2722  0.4667 -0.1433 -0.0304 -0.0335  0.0685  0.1613   
10  0.2111  0.1827  0.2023  0.1510 -0.4183 -0.0839  0.2480 -0.0950 -0.0057   
11 -0.6562 -0.1771  0.5314 -0.3422  0.0060 -0.0053  0.0555 -0.0412  0.0110   
12 -0.9098 -0.1873 -0.1503  0.0537  0.0298  0.0103 -0.0232 -0.1288  0.0049   
13 -0.2948  0.7954  0.0793 -0.0140  0.1124 -0.0803 -0.1482 -0.0346  0.0859   
14  0.9450  0.1666  0.2159 -0.0522  0.0733 -0.1018 -0.0662  0.0686 -0.0169   
15  0.9385  0.1462  0.2639 -0.0913  0.0316 -0.0786 -0.0349  0.0749 -0.0111   
16  0.3169  0.0364  0.1941  0.0477  0.2597  0.3415  0.1500  0.0159  0.1809   

        9       10      11      12      13      14      15      16  
0  -0.1104 -0.1286  0.0205  0.0071  0.0345 -0.0004 -0.0034  0.0005  
1   0.0055 -0.0759  0.1517  0.0282  0.0243 -0.0301 -0.0064 -0.0050  
2   0.0577 -0.1107  0.1535  0.0388 -0.0435 -0.0156  0.0027 -0.0033  
3  -0.1634  0.1131  0.0313  0.0235  0.0386 -0.0574 -0.0062 -0.0006  
4  -0.0011 -0.0466 -0.0163  0.0756  0.0985  0.0618 -0.0058  0.0011  
5   0.0536  0.0524 -0.0461  0.1545  0.0051 -0.0030  0.0016  0.0022  
6   0.0154  0.0040  0.0165  0.0298  0.0276 -0.0076 -0.0023 -0.0020  
7   0.0108  0.1365  0.1534 -0.0046  0.0153  0.0705  0.0031  0.0014  
8   0.2008 -0.0219 -0.0036 -0.0158 -0.0002  0.0022  0.0030  0.0032  
9   0.1253 -0.0338 -0.0054 -0.0447  0.0589 -0.0204 -0.0048  0.0002  
10 -0.0708  0.0007  0.0575  0.0415 -0.0287  0.0347  0.0025  0.0019  
11 -0.0492 -0.0075  0.0197 -0.1519  0.0368  0.0210 -0.0117 -0.0020  
12 -0.0576 -0.0995  0.0122 -0.0002  0.0276 -0.0150  0.0229  0.0172  
13 -0.0826 -0.1028 -0.0541 -0.0001 -0.0571  0.0555  0.0059 -0.0022  
14  0.0235  0.0368  0.0488 -0.0231 -0.0362 -0.0015 -0.0460  0.0144  
15  0.0141  0.0501  0.0364 -0.0359  0.0014 -0.0049  0.0734  0.0028  
16 -0.0640  0.0121  0.0117  0.0173 -0.0296 -0.0104  0.0024  0.0021

In [158]:
pd.DataFrame(np.sort(D)).T

0      1      2      3      4      5      6      7      8      9   \
0 0.0006 0.0084 0.0188 0.0278 0.0626 0.0848 0.0971 0.1239 0.1550 0.1824   

      10     11     12     13     14     15     16  
0 0.2008 0.2821 0.5423 0.7100 1.1807 2.2645 6.3967

In [159]:
pd.DataFrame(np.sort(eigenvalues)).T

0       1       2       3       4       5       6      7      8   \
0 -0.2008 -0.1550 -0.1239 -0.0971 -0.0626 -0.0278 -0.0084 0.0006 0.0188   

      9      10     11     12     13     14     15     16  
0 0.0848 0.1824 0.2821 0.5423 0.7100 1.1807 2.2645 6.3967

In [139]:
principal_factor_method(final)

0       1       2       3
0 -0.3620  0.5729 -0.3125 -0.2019
1 -0.5573  0.6024  0.0920  0.2751
2  0.4277 -0.0578  0.4933  0.1422
3 -0.0015  0.4064  0.6090 -0.2647
4  0.8288  0.3121 -0.1079 -0.0473
5  0.7171  0.4543 -0.2437  0.0900
6 -0.0502  0.3159  0.1551  0.1253

In [104]:
X_corr = np.corrcoef(final, rowvar=False)
X_corr_inv = np.linalg.inv(X_corr)
X_corr_inv_diag = np.diag(X_corr_inv)
R = 1 - (1 / X_corr_inv_diag)
np.fill_diagonal(X_corr, R)
eigenvalues, _ = np.linalg.eig(X_corr)
eigenvectors, _, _ = randomized_svd(X_corr, n_components=X_corr.shape[1], random_state=1234567890)
p_index = eigenvalues > 0
eigenvalues = eigenvalues[p_index]
eigenvectors = eigenvectors[:, p_index]

In [105]:
eigenvalues

array([1.82817372, 1.26323065, 0.81545216, 0.23280422])

In [106]:
eigenvectors

array([[-0.26775118,  0.50976639, -0.34606667, -0.41839396],
       [-0.41215303,  0.53601031,  0.10191528,  0.5702476 ],
       [ 0.31634555, -0.0514643 ,  0.54628725,  0.29481451],
       [-0.00114403,  0.36154311,  0.67441812, -0.54862196],
       [ 0.61294248,  0.27765356, -0.1194454 , -0.09807081],
       [ 0.5303624 ,  0.40418014, -0.26982084,  0.18643353],
       [-0.03715666,  0.28109804,  0.17178791,  0.25978295]])

In [85]:
eigenvalues

array([ 1.82817372,  1.26323065,  0.81545216,  0.23280422, -0.03228917,
       -0.26740915, -0.17028201])

In [107]:
eigenvectors * np.sqrt(eigenvalues)

array([[-0.3620263 ,  0.57294446, -0.31250647, -0.20187421],
       [-0.55727201,  0.60244093,  0.09203193,  0.27514327],
       [ 0.42773073, -0.05784254,  0.49331044,  0.14224738],
       [-0.00154684,  0.40635108,  0.60901568, -0.26470894],
       [ 0.82875936,  0.31206465, -0.10786205, -0.04731896],
       [ 0.71710287,  0.45427234, -0.24365467,  0.08995378],
       [-0.0502395 ,  0.31593602,  0.15512859,  0.12534473]])

In [143]:
X_corr = np.corrcoef(final, rowvar=False)
X_corr_inv = np.linalg.inv(X_corr)
X_corr_inv_diag = np.diag(X_corr_inv)
R = 1 - (1 / X_corr_inv_diag)
np.fill_diagonal(X_corr, R)
eigenvalues, _ = np.linalg.eig(X_corr)
eigenvectors, D, _ = randomized_svd(X_corr, n_components=X_corr.shape[1], random_state=1234567890)
e =np.abs(eigenvalues)
D

array([1.82817372, 1.26323065, 0.81545216, 0.26740915, 0.23280422,
       0.17028201, 0.03228917])

In [132]:
np.sort(e)[::-1]

array([1.82817372, 1.26323065, 0.81545216, 0.26740915, 0.23280422,
       0.17028201, 0.03228917])

In [128]:
eigenvalues

array([ 1.82817372,  1.26323065,  0.81545216,  0.23280422, -0.03228917,
       -0.26740915, -0.17028201])

In [109]:
eigenvectors

array([[-0.26775118,  0.50976639, -0.34606667, -0.41839396, -0.22738087,
        -0.18668067,  0.53579862],
       [-0.41215303,  0.53601031,  0.10191528,  0.5702476 , -0.32074341,
         0.08042834, -0.3129037 ],
       [ 0.31634555, -0.0514643 ,  0.54628725,  0.29481451, -0.38042629,
        -0.31011385,  0.52061194],
       [-0.00114403,  0.36154311,  0.67441812, -0.54862196,  0.12681366,
        -0.06324911, -0.30557695],
       [ 0.61294248,  0.27765356, -0.1194454 , -0.09807081, -0.34215396,
         0.63641704, -0.03505644],
       [ 0.5303624 ,  0.40418014, -0.26982084,  0.18643353,  0.30677389,
        -0.55577515, -0.21165339],
       [-0.03715666,  0.28109804,  0.17178791,  0.25978295,  0.68806699,
         0.38026028,  0.45229519]])

In [144]:
pd.DataFrame(eigenvectors * np.sqrt(D))

0       1       2       3       4       5       6
0 -0.3620  0.5729 -0.3125 -0.2164 -0.1097 -0.0770  0.0963
1 -0.5573  0.6024  0.0920  0.2949 -0.1548  0.0332 -0.0562
2  0.4277 -0.0578  0.4933  0.1525 -0.1836 -0.1280  0.0935
3 -0.0015  0.4064  0.6090 -0.2837  0.0612 -0.0261 -0.0549
4  0.8288  0.3121 -0.1079 -0.0507 -0.1651  0.2626 -0.0063
5  0.7171  0.4543 -0.2437  0.0964  0.1480 -0.2293 -0.0380
6 -0.0502  0.3159  0.1551  0.1343  0.3320  0.1569  0.0813

In [145]:
D

array([1.82817372, 1.26323065, 0.81545216, 0.26740915, 0.23280422,
       0.17028201, 0.03228917])

In [ ]:
X_corr = np.corrcoef(final, rowvar=False)
X_corr_inv = np.linalg.inv(X_corr)
X_corr_inv_diag = np.diag(X_corr_inv)
R = 1 - (1 / X_corr_inv_diag)
np.fill_diagonal(X_corr, R)
eigenvalues, _ = np.linalg.eig(X_corr)
eigenvectors, _, _ = randomized_svd(X_corr, n_components=X_corr.shape[1], random_state=1234567890)

In [88]:
X_corr = np.corrcoef(final, rowvar=False)
X_corr_inv = np.linalg.inv(X_corr)
X_corr_inv_diag = np.diag(X_corr_inv)
R = 1 - (1 / X_corr_inv_diag)
np.fill_diagonal(X_corr, R)
eigenvalues, C = np.linalg.eig(np.corrcoef(final, rowvar=False))
eigenvalues

array([2.1735037 , 1.71622301, 1.33375426, 0.89603092, 0.52981505,
       0.12449408, 0.22617897])

In [82]:
C

array([[-0.26775118, -0.50976639,  0.34606667, -0.22738087,  0.53579862,
         0.41839396, -0.18668067],
       [-0.41215303, -0.53601031, -0.10191528, -0.32074341, -0.3129037 ,
        -0.5702476 ,  0.08042834],
       [ 0.31634555,  0.0514643 , -0.54628725, -0.38042629,  0.52061194,
        -0.29481451, -0.31011385],
       [-0.00114403, -0.36154311, -0.67441812,  0.12681366, -0.30557695,
         0.54862196, -0.06324911],
       [ 0.61294248, -0.27765356,  0.1194454 , -0.34215396, -0.03505644,
         0.09807081,  0.63641704],
       [ 0.5303624 , -0.40418014,  0.26982084,  0.30677389, -0.21165339,
        -0.18643353, -0.55577515],
       [-0.03715666, -0.28109804, -0.17178791,  0.68806699,  0.45229519,
        -0.25978295,  0.38026028]])

In [83]:
eigenvectors

array([[-0.26775118,  0.50976639, -0.34606667, -0.41839396, -0.22738087,
        -0.18668067,  0.53579862],
       [-0.41215303,  0.53601031,  0.10191528,  0.5702476 , -0.32074341,
         0.08042834, -0.3129037 ],
       [ 0.31634555, -0.0514643 ,  0.54628725,  0.29481451, -0.38042629,
        -0.31011385,  0.52061194],
       [-0.00114403,  0.36154311,  0.67441812, -0.54862196,  0.12681366,
        -0.06324911, -0.30557695],
       [ 0.61294248,  0.27765356, -0.1194454 , -0.09807081, -0.34215396,
         0.63641704, -0.03505644],
       [ 0.5303624 ,  0.40418014, -0.26982084,  0.18643353,  0.30677389,
        -0.55577515, -0.21165339],
       [-0.03715666,  0.28109804,  0.17178791,  0.25978295,  0.68806699,
         0.38026028,  0.45229519]])

In [77]:
eigenvalues

array([ 1.82817372,  1.26323065,  0.81545216,  0.23280422, -0.03228917,
       -0.17028201, -0.26740915])

In [70]:
n = 0
for i in eigenvalues:
    if i >= 0:
        n += 1
print(n)

4


In [140]:
X_corr = np.corrcoef(final, rowvar=False)
X_corr_inv = np.linalg.inv(X_corr)
X_corr_inv_diag = np.diag(X_corr_inv)
R = 1 - (1 / X_corr_inv_diag)
np.fill_diagonal(X_corr, R)
eigenvalues, _ = np.linalg.eig(X_corr)
eigenvectors, _, _ = randomized_svd(X_corr, n_components=X_corr.shape[1], random_state=1234567890)
idx = eigenvalues.argsort()[::-1]
eigenvalues = eigenvalues[idx]
eigenvectors = eigenvectors[:, idx]
p_index = eigenvalues > 0
eigenvalues = eigenvalues[p_index]
eigenvectors = eigenvectors[:, p_index]

In [141]:
eigenvalues

array([1.82817372, 1.26323065, 0.81545216, 0.23280422])

In [135]:
idx

array([0, 1, 2, 3, 4, 6, 5], dtype=int64)

In [54]:
pd.DataFrame(final).shape[1]

7

In [50]:
D

array([1.82817372, 1.26323065, 0.81545216, 0.26740915, 0.23280422,
       0.17028201, 0.03228917])

In [49]:
loadings = C * np.sqrt(eigenvalues[::-1])
pd.DataFrame(loadings).dropna(axis=1)

C:\Users\HP\AppData\Local\Temp\ipykernel_23872\1974874582.py:1: RuntimeWarning: invalid value encountered in sqrt
  loadings = C * np.sqrt(eigenvalues[::-1])


0         1         2         3
0 -0.362026  0.572944 -0.312506 -0.201874
1 -0.557272  0.602441  0.092032  0.275143
2  0.427731 -0.057843  0.493310  0.142247
3 -0.001547  0.406351  0.609016 -0.264709
4  0.828759  0.312065 -0.107862 -0.047319
5  0.717103  0.454272 -0.243655  0.089954
6 -0.050240  0.315936  0.155129  0.125345

In [34]:
for i, (eigenvalue, eigenvector) in enumerate(zip(eigenvalues, eigenvectors.T)):
    print(f"Autovalor {i+1}: {eigenvalue}")
    print(f"Autovector {i+1}: {eigenvector}\n")


Autovalor 1: -0.26740914748499967
Autovector 1: [ 0.41839396 -0.5702476  -0.29481451  0.54862196  0.09807081 -0.18643353
 -0.25978295]

Autovalor 2: -0.1702820100664893
Autovector 2: [-0.18668067  0.08042834 -0.31011385 -0.06324911  0.63641704 -0.55577515
  0.38026028]

Autovalor 3: -0.032289170090544744
Autovector 3: [ 0.53579862 -0.3129037   0.52061194 -0.30557695 -0.03505644 -0.21165339
  0.45229519]

Autovalor 4: 0.23280422172295018
Autovector 4: [ 0.22738087  0.32074341  0.38042629 -0.12681366  0.34215396 -0.30677389
 -0.68806699]

Autovalor 5: 0.8154521559803469
Autovector 5: [-0.34606667  0.10191528  0.54628725  0.67441812 -0.1194454  -0.26982084
  0.17178791]

Autovalor 6: 1.2632306539629632
Autovector 6: [ 0.50976639  0.53601031 -0.0514643   0.36154311  0.27765356  0.40418014
  0.28109804]

Autovalor 7: 1.8281737196653418
Autovector 7: [ 0.26775118  0.41215303 -0.31634555  0.00114403 -0.61294248 -0.5303624
  0.03715666]



In [33]:
eigenvalues

array([-0.26740915, -0.17028201, -0.03228917,  0.23280422,  0.81545216,
        1.26323065,  1.82817372])

In [35]:
eigenvectors

array([[ 0.41839396, -0.18668067,  0.53579862,  0.22738087, -0.34606667,
         0.50976639,  0.26775118],
       [-0.5702476 ,  0.08042834, -0.3129037 ,  0.32074341,  0.10191528,
         0.53601031,  0.41215303],
       [-0.29481451, -0.31011385,  0.52061194,  0.38042629,  0.54628725,
        -0.0514643 , -0.31634555],
       [ 0.54862196, -0.06324911, -0.30557695, -0.12681366,  0.67441812,
         0.36154311,  0.00114403],
       [ 0.09807081,  0.63641704, -0.03505644,  0.34215396, -0.1194454 ,
         0.27765356, -0.61294248],
       [-0.18643353, -0.55577515, -0.21165339, -0.30677389, -0.26982084,
         0.40418014, -0.5303624 ],
       [-0.25978295,  0.38026028,  0.45229519, -0.68806699,  0.17178791,
         0.28109804,  0.03715666]])

In [31]:
columns_to_exclude = [3, 5, 6]

# Crear un array con las columnas que se van a conservar
columns_to_keep = np.setdiff1d(np.arange(loadings.shape[1]), columns_to_exclude)

# Filtrar el array
filtered_data = loadings[:, columns_to_keep]

In [25]:
loadings[:,0:5]

array([[-0.3620263 , -0.57294446,  0.31250647,  0.21635829, -0.10971079],
       [-0.55727201, -0.60244093, -0.09203193, -0.29488426, -0.15475802],
       [ 0.42773073,  0.05784254, -0.49331044, -0.15245336, -0.18355489],
       [-0.00154684, -0.40635108, -0.60901568,  0.28370129,  0.06118732],
       [ 0.82875936, -0.31206465,  0.10786205,  0.050714  , -0.16508857],
       [ 0.71710287, -0.45427234,  0.24365467, -0.09640779,  0.14801776],
       [-0.0502395 , -0.31593602, -0.15512859, -0.13433797,  0.33199088]])

In [32]:
1 - pd.DataFrame(np.diag(np.sum((filtered_data**2), axis=1)))

0         1         2         3         4         5         6
0  0.430975  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
1  1.000000  0.294093  1.000000  1.000000  1.000000  1.000000  1.000000
2  1.000000  1.000000  0.536653  1.000000  1.000000  1.000000  1.000000
3  1.000000  1.000000  1.000000  0.460232  1.000000  1.000000  1.000000
4  1.000000  1.000000  1.000000  1.000000  0.176885  1.000000  1.000000
5  1.000000  1.000000  1.000000  1.000000  1.000000  0.198123  1.000000
6  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  0.763378

In [19]:
eigenvalues

array([-0.26740915, -0.17028201, -0.03228917,  0.23280422,  0.81545216,
        1.26323065,  1.82817372])

In [6]:
loadings

array([nan, nan, nan, nan, nan, nan, nan])

In [78]:
from sklearn.utils.extmath import randomized_svd
E, R, T = randomized_svd(data_cor, n_components=7, random_state=1234567890)

E

array([[-0.2678,  0.5098, -0.3461, -0.4184, -0.2274, -0.1867,  0.5358],
       [-0.4122,  0.536 ,  0.1019,  0.5702, -0.3207,  0.0804, -0.3129],
       [ 0.3163, -0.0515,  0.5463,  0.2948, -0.3804, -0.3101,  0.5206],
       [-0.0011,  0.3615,  0.6744, -0.5486,  0.1268, -0.0632, -0.3056],
       [ 0.6129,  0.2777, -0.1194, -0.0981, -0.3422,  0.6364, -0.0351],
       [ 0.5304,  0.4042, -0.2698,  0.1864,  0.3068, -0.5558, -0.2117],
       [-0.0372,  0.2811,  0.1718,  0.2598,  0.6881,  0.3803,  0.4523]])

In [83]:
R

array([1.8282, 1.2632, 0.8155, 0.2674, 0.2328, 0.1703, 0.0323])

In [84]:
E * np.sqrt(R)

array([[-0.362 ,  0.5729, -0.3125, -0.2164, -0.1097, -0.077 ,  0.0963],
       [-0.5573,  0.6024,  0.092 ,  0.2949, -0.1548,  0.0332, -0.0562],
       [ 0.4277, -0.0578,  0.4933,  0.1525, -0.1836, -0.128 ,  0.0935],
       [-0.0015,  0.4064,  0.609 , -0.2837,  0.0612, -0.0261, -0.0549],
       [ 0.8288,  0.3121, -0.1079, -0.0507, -0.1651,  0.2626, -0.0063],
       [ 0.7171,  0.4543, -0.2437,  0.0964,  0.148 , -0.2293, -0.038 ],
       [-0.0502,  0.3159,  0.1551,  0.1343,  0.332 ,  0.1569,  0.0813]])

In [81]:
D

array([1.8282, 1.2632, 0.8155, 0.2674, 0.2328, 0.1703, 0.0323])

In [79]:
C

array([[-0.2678, -0.5098,  0.3461, -0.4184,  0.2274, -0.1867, -0.5358],
       [-0.4122, -0.536 , -0.1019,  0.5702,  0.3207,  0.0804,  0.3129],
       [ 0.3163,  0.0515, -0.5463,  0.2948,  0.3804, -0.3101, -0.5206],
       [-0.0011, -0.3615, -0.6744, -0.5486, -0.1268, -0.0632,  0.3056],
       [ 0.6129, -0.2777,  0.1194, -0.0981,  0.3422,  0.6364,  0.0351],
       [ 0.5304, -0.4042,  0.2698,  0.1864, -0.3068, -0.5558,  0.2117],
       [-0.0372, -0.2811, -0.1718,  0.2598, -0.6881,  0.3803, -0.4523]])

In [160]:
# Supongamos que estos son tus arrays
abs_array = np.array([1.3, 2.5, 0.7, 1.5, 4.2])  # Array en valor absoluto
orig_array = np.array([1.3, -2.5, 0.7, -1.5, 4.2])  # Array original

# Encuentra los índices donde el array original es negativo
negative_indices = np.where(orig_array < 0)[0]

# Filtra el primer array para obtener solo los valores correspondientes a esos índices
filtered_abs_array = abs_array[negative_indices]

In [161]:
filtered_abs_array

array([2.5, 1.5])

In [162]:
data_array = np.array([[10, 20, 30, 40, 50],
                       [60, 70, 80, 90, 100],
                       [110, 120, 130, 140, 150],
                       [160, 170, 180, 190, 200],
                       [210, 220, 230, 240, 250]])

In [163]:
pd.DataFrame(data_array)

0    1    2    3    4
0   10   20   30   40   50
1   60   70   80   90  100
2  110  120  130  140  150
3  160  170  180  190  200
4  210  220  230  240  250

In [164]:
data_array[:, negative_indices]

array([[ 20,  40],
       [ 70,  90],
       [120, 140],
       [170, 190],
       [220, 240]])

In [167]:
abs_array = np.array([4.2, 2.5, 1.5, 1.3, 0.7])  # Array en valor absoluto
orig_array = np.array([1.3, -2.5, 0.7, -1.5, 4.2])  # Array original

# Encuentra los índices donde el array original es negativo
negative_indices = np.where(orig_array > 0)[0]

# Ahora, usando estos índices como filtro para data_array
# Supongamos que tienes un array de datos de 5x5
data_array = np.array([[10, 20, 30, 40, 50],
                       [60, 70, 80, 90, 100],
                       [110, 120, 130, 140, 150],
                       [160, 170, 180, 190, 200],
                       [210, 220, 230, 240, 250]])

# Filtra las columnas en data_array usando los índices obtenidos
filtered_columns = data_array[:, negative_indices]
pd.DataFrame(filtered_columns)

0    1    2
0   10   30   50
1   60   80  100
2  110  130  150
3  160  180  200
4  210  230  250

In [169]:
import numpy as np

# Tus arrays
abs_array = np.array([4.2, 2.5, 1.5, 1.3, 0.7])  # Array en valor absoluto
orig_array = np.array([1.3, -2.5, 0.7, -1.5, 4.2])  # Array original

# Encuentra los índices donde el array original es positivo
positive_indices = np.where(orig_array > 0)[0]

# Filtra abs_array para conservar solo los índices que son positivos en orig_array
filtered_indices = [i for i in positive_indices if orig_array[i] > 0]

# Supongamos que tienes un array de datos de 5x5
data_array = np.array([[10, 20, 30, 40, 50],
                       [60, 70, 80, 90, 100],
                       [110, 120, 130, 140, 150],
                       [160, 170, 180, 190, 200],
                       [210, 220, 230, 240, 250]])

# Filtra las columnas en data_array usando los índices de abs_array que corresponden a los positivos de orig_array
filtered_columns = data_array[:, filtered_indices]

# Imprimir los resultados
print("Índices de elementos positivos en orig_array:", positive_indices)
print("Columnas filtradas de data_array (usando los índices de abs_array):\n", filtered_columns)



Índices de elementos positivos en orig_array: [0 2 4]
Columnas filtradas de data_array (usando los índices de abs_array):
 [[ 10  30  50]
 [ 60  80 100]
 [110 130 150]
 [160 180 200]
 [210 230 250]]


In [170]:
import numpy as np

# Tus arrays
abs_array = np.array([4.2, 2.5, 1.5, 1.3, 0.7])  # Array en valor absoluto
orig_array = np.array([1.3, -2.5, 0.7, -1.5, 4.2])  # Array original

# Inicializamos una lista para guardar los índices encontrados
found_indices = []

# Buscar cada elemento de abs_array en orig_array
for idx, value in enumerate(abs_array):
    if value in orig_array:
        found_indices.append(idx)

# Convertir la lista a un array de NumPy si es necesario
found_indices = np.array(found_indices)

# Imprimir resultados
print("Índices de elementos de abs_array encontrados en orig_array:", found_indices)


Índices de elementos de abs_array encontrados en orig_array: [0 3 4]


In [171]:
found_indices = [idx for idx, value in enumerate(abs_array) if value in orig_array]

array([0, 3, 4])