In [28]:
import pandas as pd
import numpy as np

np.set_printoptions(precision=4)
pd.set_option('display.float_format', '{:.4f}'.format)
# path = r"C:\Users\HP\OneDrive\Escritorio\David Guzzi\DiTella\MEC\Materias\2024 2T\[MT04] Análisis Estadístico Multivariado\Guías prácticas\Problem Set 5-20240906\FA.xlsx"

# df = pd.read_excel(path)
# df


In [3]:
# df.to_stata(r"C:\Users\HP\OneDrive\Escritorio\David Guzzi\DiTella\MEC\Materias\2024 2T\[MT04] Análisis Estadístico Multivariado\Guías prácticas\Problem Set 5-20240906\FA.dta")

In [22]:
data = np.array([
    [1, 5, 5, 1, 1],
    [8, 9, 7, 9, 8],
    [9, 8, 9, 9, 8],
    [9, 9, 9, 9, 9],
    [1, 9, 1, 1, 9],
    [9, 7, 7, 9, 9],
    [9, 7, 9, 9, 7]
])

In [35]:
data_cov = np.cov(data, rowvar=False)
data_cov_inv = np.linalg.inv(data_cov)
data_cov_inv_d = np.diag(data_cov_inv)
data_cov_d = np.diag(data_cov)

data_cov_d - (1/data_cov_inv_d)


array([14.619 ,  2.2381,  8.5714, 15.2381,  8.2381])

In [36]:
data_cov_d

array([14.619 ,  2.2381,  8.5714, 15.2381,  8.2381])

In [34]:
data_cor = np.corrcoef(data, rowvar=False)
data_inv = np.linalg.inv(data_cor)
data_inv_d = np.diag(data_inv)
com = 1 - (1/data_inv_d)
pd.DataFrame(data_inv)

0                     1                     2  \
0 -2644311556751862.0000 -344882461543805.6875  674929534706399.2500   
1  -344882461543805.9375  -44981050730122.6016   88027206440106.9531   
2   674929534706398.2500   88027206440106.7812 -172267853860047.3438   
3  1799812092550373.0000  234739217173618.4062 -459380943626833.1875   
4   661675771094734.5000   86298593710095.0156 -168884986026386.2812   

                       3                     4  
0  1799812092550371.7500  661675771094734.8750  
1   234739217173618.3438   86298593710095.0938  
2  -459380943626832.1875 -168884986026386.1250  
3 -1225015849671483.2500 -450359962737050.1875  
4  -450359962737049.6250 -165568548432159.7188

In [30]:
data_inv_d

array([-2.6443e+15, -4.4981e+13, -1.7227e+14, -1.2250e+15, -1.6557e+14])

In [18]:
data_cor = np.corrcoef(data, rowvar=False)
C, D, V = np.linalg.svd(data_cor, full_matrices=False)
loadings = C * np.sqrt(D)
pd.DataFrame(loadings)


0         1         2         3             4
0 -0.969455  0.231148  0.078451 -0.023928 -8.292461e-09
1 -0.519402 -0.806945 -0.280349 -0.021568 -1.081538e-09
2 -0.784517  0.587241 -0.167545  0.107744  2.116553e-09
3 -0.970870  0.209949  0.039351 -0.108552  5.644142e-09
4 -0.703964 -0.666927  0.231258  0.078502  2.074990e-09

In [49]:
corr = df.corr().values
max = np.array([corr[:, i][corr[:, i] < 1].max() for i in range(corr.shape[1])])
corr_max = corr.copy()
np.fill_diagonal(corr_max, max)
corr_max


array([[0.26418458, 0.26418458],
       [0.26418458, 0.26418458]])

In [47]:
C, D, V = np.linalg.svd(corr_max, full_matrices=False)
D_o = sorted(D, reverse=True)
loadings = C * np.sqrt(D_o)
pd.DataFrame(loadings)

0             1
0 -0.513989 -3.239622e-09
1 -0.513989  3.239622e-09

In [48]:
D_o

[0.5283691548027929, 2.0990295514250575e-17]

In [36]:
# data = np.array([
#     [1, 5, 5, 1, 1],
#     [8, 9, 7, 9, 8],
#     [9, 8, 9, 9, 8],
#     [9, 9, 9, 9, 9],
#     [1, 9, 1, 1, 9],
#     [9, 7, 7, 9, 9],
#     [9, 7, 9, 9, 7]
# ])
# correlacion = np.corrcoef(data, rowvar=False)
# correlacion


R = np.array([
    [1.000, 0.296, 0.881, 0.995, 0.545],
    [0.296, 1.000, -0.022, 0.326, 0.837],
    [0.881, -0.022, 1.000, 0.867, 0.130],
    [0.995, 0.326, 0.867, 1.000, 0.544],
    [0.545, 0.837, 0.130, 0.544, 1.000]
])

In [37]:
# Obtener el máximo de cada columna
maximos = np.array([R[:, i][R[:, i] < 1].max() for i in range(R.shape[1])])

# Asignar los máximos a la diagonal principal
corr_m = R.copy()
np.fill_diagonal(corr_m, maximos)

corr_m

array([[ 0.995,  0.296,  0.881,  0.995,  0.545],
       [ 0.296,  0.837, -0.022,  0.326,  0.837],
       [ 0.881, -0.022,  0.881,  0.867,  0.13 ],
       [ 0.995,  0.326,  0.867,  0.995,  0.544],
       [ 0.545,  0.837,  0.13 ,  0.544,  0.837]])

In [40]:
C, D, V = np.linalg.svd(corr_m, full_matrices=False)
D_o = sorted(D, reverse=True)
D_o

[3.2017093090737263,
 1.3944390756838965,
 0.08030346115353326,
 0.029317098629336614,
 0.00016202223342619344]

In [41]:
C

array([[-0.54801288,  0.17703557,  0.43482521,  0.4128932 , -0.55568564],
       [-0.27205858, -0.6555723 ,  0.35020688, -0.60069019, -0.11285179],
       [-0.43126509,  0.46085993, -0.49431898, -0.55340045, -0.22586551],
       [-0.54855994,  0.15869823,  0.20994059,  0.04883377,  0.79210926],
       [-0.37250292, -0.5489138 , -0.63234157,  0.40006713, -0.00506389]])

In [43]:
loadings = C * np.sqrt(D_o)
pd.DataFrame(loadings)

0         1         2         3         4
0 -0.980577  0.209055  0.123220  0.070697 -0.007073
1 -0.486803 -0.774142  0.099241 -0.102852 -0.001436
2 -0.771676  0.544213 -0.140079 -0.094755 -0.002875
3 -0.981556  0.187401  0.059493  0.008361  0.010083
4 -0.666531 -0.648192 -0.179192  0.068500 -0.000064

In [19]:


from numpy.linalg import eigh
eigenvalues, eigenvectors = eigh(correlacion)

eigenvectors


array([[-0.78859185, -0.13680245,  0.19148531,  0.18636648, -0.5366646 ],
       [-0.10285153, -0.12331285, -0.68428658, -0.65061165, -0.28752715],
       [ 0.20127883,  0.61600625, -0.40895166,  0.47347196, -0.4342879 ],
       [ 0.53674354, -0.62062607,  0.0960492 ,  0.16927454, -0.53744798],
       [ 0.19732626,  0.44881913,  0.56446288, -0.53771969, -0.38969594]])

In [21]:
C, D, V = np.linalg.svd(correlacion, full_matrices=False)
D_o = sorted(D, reverse=True)
D_o

[3.263245029034827,
 1.5383125277506948,
 0.16785005049901378,
 0.03059239271546363,
 1.1057635293408557e-16]

In [12]:
C

array([[-0.53673007,  0.18598191,  0.18991841, -0.12479313, -0.79100521],
       [-0.28746718, -0.65056657, -0.68488713, -0.11981409, -0.10344059],
       [-0.43435455,  0.47368768, -0.40694897,  0.61366343,  0.2115794 ],
       [-0.53739095,  0.16927968,  0.09532905, -0.62938958,  0.52662747],
       [-0.38965441, -0.53771576,  0.5658317 ,  0.44424905,  0.20373628]])

In [22]:
loadings = C * np.sqrt(D_o)
loadings

array([[-9.69455305e-01,  2.31147968e-01,  7.84505865e-02,
        -2.39276806e-02, -8.29246060e-09],
       [-5.19402104e-01, -8.06945347e-01, -2.80348839e-01,
        -2.15682580e-02, -1.08153830e-09],
       [-7.84517390e-01,  5.87241242e-01, -1.67545477e-01,
         1.07743689e-01,  2.11655338e-09],
       [-9.70870447e-01,  2.09949055e-01,  3.93508828e-02,
        -1.08551727e-01,  5.64414236e-09],
       [-7.03964442e-01, -6.66926884e-01,  2.31257661e-01,
         7.85015230e-02,  2.07499008e-09]])

In [16]:
array_cuadrado = np.square(loadings)

# Sumar los cuadrados por cada fila
suma_filas = np.sum(array_cuadrado, axis=1)
suma_filas

array([1., 1., 1., 1., 1.])

In [51]:
data = np.array([
    [1, 5, 5, 1, 1],
    [8, 9, 7, 9, 8],
    [9, 8, 9, 9, 8],
    [9, 9, 9, 9, 9],
    [1, 9, 1, 1, 9],
    [9, 7, 7, 9, 9],
    [9, 7, 9, 9, 7]
])

pd.DataFrame(data).to_stata(r"C:\Users\HP\OneDrive\Escritorio\David Guzzi\DiTella\MEC\Materias\2024 2T\[MT04] Análisis Estadístico Multivariado\Guías prácticas\Problem Set 5-20240906\FA.dta")

C:\Users\HP\AppData\Local\Temp\ipykernel_13820\3666724846.py:11: InvalidColumnName: 
Not all pandas column names were valid Stata variable names.
The following replacements have been made:

    0   ->   _0
    1   ->   _1
    2   ->   _2
    3   ->   _3
    4   ->   _4

If this is not what you expect, please make sure you have Stata-compliant
column names in your DataFrame (strings only, max 32 characters, only
alphanumerics and underscores, no Stata reserved words)

  pd.DataFrame(data).to_stata(r"C:\Users\HP\OneDrive\Escritorio\David Guzzi\DiTella\MEC\Materias\2024 2T\[MT04] Análisis Estadístico Multivariado\Guías prácticas\Problem Set 5-20240906\FA.dta")


In [50]:
final = pd.read_excel(r"C:\Users\HP\OneDrive\Escritorio\David Guzzi\Github\MECMT04\TP AEM - database.xlsx")

final.columns = [f"X{i}" for i in range(len(final.columns))]

# final.to_stata(r"C:\Users\HP\OneDrive\Escritorio\David Guzzi\DiTella\MEC\Materias\2024 2T\[MT04] Análisis Estadístico Multivariado\Guías prácticas\Problem Set 5-20240906\final.dta")

In [48]:
final.head()

X0   X1      X2      X3     X4     X5     X6     X7      X8
0  Argentina  ARG 42.5908 14.9117 0.8813 1.0457 5.3186 7.3309  8.0090
1  Australia  AUS 47.1238  3.9746 2.1059 0.6622 2.1131 2.5583 13.8760
2    Austria  AUT 32.1281 16.0631 1.5208 1.8149 1.0524 3.6561 41.4850
3    Belgium  BEL 44.7960 28.3120 1.2331 1.0485 0.6700 0.9196  1.9590
4     Canada  CAN  6.4344  4.3107 3.6934 0.8181 1.6971 1.5105 18.5180

In [51]:
final = final.iloc[:,2:].values
data_cor = np.corrcoef(final, rowvar=False)
data_inv = np.linalg.inv(data_cor)
data_inv_d = np.diag(data_inv)
com = 1 - (1/data_inv_d)
np.fill_diagonal(data_cor, com)
C, D, V = np.linalg.svd(data_cor, full_matrices=False, hermitian=True)
loadings = C * np.sqrt(D)
pd.DataFrame(loadings)

0       1       2       3       4       5       6
0 -0.3620 -0.5729  0.3125 -0.2164  0.1097 -0.0770 -0.0963
1 -0.5573 -0.6024 -0.0920  0.2949  0.1548  0.0332  0.0562
2  0.4277  0.0578 -0.4933  0.1525  0.1836 -0.1280 -0.0935
3 -0.0015 -0.4064 -0.6090 -0.2837 -0.0612 -0.0261  0.0549
4  0.8288 -0.3121  0.1079 -0.0507  0.1651  0.2626  0.0063
5  0.7171 -0.4543  0.2437  0.0964 -0.1480 -0.2293  0.0380
6 -0.0502 -0.3159 -0.1551  0.1343 -0.3320  0.1569 -0.0813

In [59]:
C

array([[-0.2678, -0.5098,  0.3461, -0.4184,  0.2274, -0.1867, -0.5358],
       [-0.4122, -0.536 , -0.1019,  0.5702,  0.3207,  0.0804,  0.3129],
       [ 0.3163,  0.0515, -0.5463,  0.2948,  0.3804, -0.3101, -0.5206],
       [-0.0011, -0.3615, -0.6744, -0.5486, -0.1268, -0.0632,  0.3056],
       [ 0.6129, -0.2777,  0.1194, -0.0981,  0.3422,  0.6364,  0.0351],
       [ 0.5304, -0.4042,  0.2698,  0.1864, -0.3068, -0.5558,  0.2117],
       [-0.0372, -0.2811, -0.1718,  0.2598, -0.6881,  0.3803, -0.4523]])

In [54]:
np.sort(D)

array([0.0323, 0.1703, 0.2328, 0.2674, 0.8155, 1.2632, 1.8282])

In [58]:
from numpy.linalg import eigh
eigenvalues, eigenvectors = eigh(data_cor)
np.sort(eigenvalues)

eigenvectors

array([[-0.4184, -0.1867, -0.5358,  0.2274,  0.3461, -0.5098, -0.2678],
       [ 0.5702,  0.0804,  0.3129,  0.3207, -0.1019, -0.536 , -0.4122],
       [ 0.2948, -0.3101, -0.5206,  0.3804, -0.5463,  0.0515,  0.3163],
       [-0.5486, -0.0632,  0.3056, -0.1268, -0.6744, -0.3615, -0.0011],
       [-0.0981,  0.6364,  0.0351,  0.3422,  0.1194, -0.2777,  0.6129],
       [ 0.1864, -0.5558,  0.2117, -0.3068,  0.2698, -0.4042,  0.5304],
       [ 0.2598,  0.3803, -0.4523, -0.6881, -0.1718, -0.2811, -0.0372]])

In [61]:
eigenvalues

array([-0.2674, -0.1703, -0.0323,  0.2328,  0.8155,  1.2632,  1.8282])

In [60]:
loadings3 = C * np.sqrt(eigenvalues)
loadings3

C:\Users\HP\AppData\Local\Temp\ipykernel_11736\3645955264.py:1: RuntimeWarning: invalid value encountered in sqrt
  loadings3 = C * np.sqrt(eigenvalues)


array([[    nan,     nan,     nan, -0.2019,  0.2053, -0.2098, -0.7245],
       [    nan,     nan,     nan,  0.2751,  0.2896,  0.0904,  0.4231],
       [    nan,     nan,     nan,  0.1422,  0.3435, -0.3485, -0.7039],
       [    nan,     nan,     nan, -0.2647, -0.1145, -0.0711,  0.4132],
       [    nan,     nan,     nan, -0.0473,  0.309 ,  0.7153,  0.0474],
       [    nan,     nan,     nan,  0.09  , -0.277 , -0.6247,  0.2862],
       [    nan,     nan,     nan,  0.1253, -0.6213,  0.4274, -0.6115]])

In [67]:
import pandas as pd
import numpy as np
from scipy.linalg import eigh

# Cargar los datos desde el archivo Excel
final = pd.read_excel(r"C:\Users\HP\OneDrive\Escritorio\David Guzzi\Github\MECMT04\TP AEM - database.xlsx")

# Renombrar las columnas
final.columns = [f"X{i}" for i in range(len(final.columns))]

# Seleccionar los datos a partir de la tercera columna
final = final.iloc[:, 2:].values

# Calcular la matriz de correlación
data_cor = np.corrcoef(final, rowvar=False)

# Calcular la matriz inversa de la correlación
data_inv = np.linalg.inv(data_cor)
data_inv_d = np.diag(data_inv)

# Calcular la matriz de comunalidades
com = 1 - (1 / data_inv_d)

# Rellenar la diagonal de la matriz de correlación
np.fill_diagonal(data_cor, com)

# Paso 1: Descomposición SVD
C, D, V = np.linalg.svd(data_cor, full_matrices=False)

# Paso 2: Obtener autovalores y autovectores
eigenvalues, eigenvectors = eigh(data_cor)

# Paso 3: Filtrar y ordenar autovalores positivos
positive_indices = eigenvalues > 0
sorted_indices = np.argsort(eigenvalues[positive_indices])[::-1]  # Índices para ordenar de mayor a menor
positive_eigenvalues = eigenvalues[positive_indices][sorted_indices]

# Filtrar los autovectores de SVD (C) usando los índices positivos


# Paso 4: Realizar la multiplicación para obtener los loadings
loadings = C @ np.sqrt(D)

# Resultados
print("Autovalores positivos ordenados:", positive_eigenvalues)
print("Autovectores de SVD correspondientes ordenados:\n", C)
print("Loadings:\n", loadings)


Autovalores positivos ordenados: [1.8282 1.2632 0.8155 0.2328]
Autovectores de SVD correspondientes ordenados:
 [[-0.2678 -0.5098  0.3461  0.4184 -0.2274  0.1867  0.5358]
 [-0.4122 -0.536  -0.1019 -0.5702 -0.3207 -0.0804 -0.3129]
 [ 0.3163  0.0515 -0.5463 -0.2948 -0.3804  0.3101  0.5206]
 [-0.0011 -0.3615 -0.6744  0.5486  0.1268  0.0632 -0.3056]
 [ 0.6129 -0.2777  0.1194  0.0981 -0.3422 -0.6364 -0.0351]
 [ 0.5304 -0.4042  0.2698 -0.1864  0.3068  0.5558 -0.2117]
 [-0.0372 -0.2811 -0.1718 -0.2598  0.6881 -0.3803  0.4523]]
Loadings:
 [-0.3425 -1.7908 -0.1222 -0.7008  0.2413  0.7494 -0.3993]
